# Generated by Django 2.2.12 on 2020-04-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('path_file', models.CharField(max_length=255)),
                ('status_log', models.CharField(max_length=15)),
            ],
        ),
    ]
